version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/mere
    binary: mere
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "mere-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: Enriquefft
    name: Mere
  draft: false
  prerelease: auto
